<a href="https://colab.research.google.com/github/Sahana-K-2002/CodeClauseInternship_LoanPrediction/blob/main/Loan_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
data=pd.read_csv('loan.csv')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252000 entries, 0 to 251999
Data columns (total 13 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   Id                 252000 non-null  int64 
 1   Income             252000 non-null  int64 
 2   Age                252000 non-null  int64 
 3   Experience         252000 non-null  int64 
 4   Married/Single     252000 non-null  object
 5   House_Ownership    252000 non-null  object
 6   Car_Ownership      252000 non-null  object
 7   Profession         252000 non-null  object
 8   CITY               252000 non-null  object
 9   STATE              252000 non-null  object
 10  CURRENT_JOB_YRS    252000 non-null  int64 
 11  CURRENT_HOUSE_YRS  252000 non-null  int64 
 12  Risk_Flag          252000 non-null  int64 
dtypes: int64(7), object(6)
memory usage: 25.0+ MB


In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['Married/Single']=le.fit_transform(data['Married/Single'])
data['House_Ownership']=le.fit_transform(data['House_Ownership'])
data['Car_Ownership']=le.fit_transform(data['Car_Ownership'])
data['Profession']=le.fit_transform(data['Profession'])
data['CITY']=le.fit_transform(data['CITY'])
data['STATE']=le.fit_transform(data['STATE'])

In [7]:
cor=data.corr()['Risk_Flag']

In [8]:
print(cor)

Id                   0.032153
Income              -0.003091
Age                 -0.021809
Experience          -0.034523
Married/Single       0.021092
House_Ownership      0.023622
Car_Ownership       -0.024036
Profession          -0.004900
CITY                 0.004575
STATE               -0.003401
CURRENT_JOB_YRS     -0.016942
CURRENT_HOUSE_YRS   -0.004375
Risk_Flag            1.000000
Name: Risk_Flag, dtype: float64


In [9]:
cls=data['Risk_Flag'].value_counts()

In [10]:
print(cls)

0    221004
1     30996
Name: Risk_Flag, dtype: int64


In [11]:
data.isnull().sum()

Id                   0
Income               0
Age                  0
Experience           0
Married/Single       0
House_Ownership      0
Car_Ownership        0
Profession           0
CITY                 0
STATE                0
CURRENT_JOB_YRS      0
CURRENT_HOUSE_YRS    0
Risk_Flag            0
dtype: int64

In [12]:
data=data.dropna()

In [13]:
x=data.drop(["Risk_Flag","Id"],axis=1)

In [14]:
y=data['Risk_Flag']

In [15]:
from imblearn.over_sampling import SMOTE
smote=SMOTE()

In [16]:
x_smote,y_smote=smote.fit_resample(x,y)

In [17]:
clscnt=y_smote.value_counts()

In [18]:
print(clscnt)

0    221004
1    221004
Name: Risk_Flag, dtype: int64


In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_smote, y_smote, test_size = 0.2, random_state = 0)

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train_n=sc.fit_transform(x_train)
x_test_n=sc.transform(x_test)

In [21]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train_n, y_train)

KNeighborsClassifier()

In [22]:
y_pred=classifier.predict(x_test_n)
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
acc=accuracy_score(y_test,y_pred)
print(acc)

[[38007  6392]
 [ 2046 41957]]
0.904549670821927


In [23]:
from sklearn.tree import DecisionTreeClassifier
dtclassifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dtclassifier.fit(x_train_n, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [24]:
y_pred=dtclassifier.predict(x_test_n)
cm=confusion_matrix(y_test,y_pred)
print(cm)
acc=accuracy_score(y_test,y_pred)
print(acc)

[[38295  6104]
 [ 2168 41835]]
0.9064274563923893


In [25]:
from sklearn.ensemble import RandomForestClassifier
rfclassifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rfclassifier.fit(x_train_n, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [26]:
y_pred=rfclassifier.predict(x_test_n)
cm=confusion_matrix(y_test,y_pred)
print(cm)
acc=accuracy_score(y_test,y_pred)
print(acc)

[[39021  5378]
 [ 1941 42062]]
0.9172077554806453


In [27]:
from xgboost import XGBClassifier
xgclassifier = XGBClassifier()
xgclassifier.fit(x_train_n, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [28]:
y_pred=xgclassifier.predict(x_test_n)
cm=confusion_matrix(y_test,y_pred)
print(cm)
acc=accuracy_score(y_test,y_pred)
print(acc)

[[37624  6775]
 [ 3787 40216]]
0.8805230650890251


In [29]:
from sklearn.ensemble import VotingClassifier
ensemble = VotingClassifier(
    estimators=[('decision_tree', dtclassifier),
                ('knn',classifier),
                ('random_forest', rfclassifier),
                ('xgboost',xgclassifier)],
    voting='hard'  # You can use 'soft' for soft voting
)

In [30]:
ensemble.fit(x_train_n,y_train)

VotingClassifier(estimators=[('decision_tree',
                              DecisionTreeClassifier(criterion='entropy',
                                                     random_state=0)),
                             ('knn', KNeighborsClassifier()),
                             ('random_forest',
                              RandomForestClassifier(criterion='entropy',
                                                     n_estimators=10,
                                                     random_state=0)),
                             ('xgboost',
                              XGBClassifier(base_score=None, booster=None,
                                            callbacks=None,
                                            colsample_bylevel=None,
                                            colsample_bynode=None,
                                            colsam...
                                            gpu_id=None, grow_policy=None,
                                            importance_type=None,
                                            interaction_constraints=None,
                                            learning_rate=None, max_bin=None,
                                            max_cat_threshold=None,
                                            max_cat_to_onehot=None,
                                            max_delta_step=None, max_depth=None,
                                            max_leaves=None,
                                            min_child_weight=None, missing=nan,
                                            monotone_constraints=None,
                                            n_estimators=100, n_jobs=None,
                                            num_parallel_tree=None,
                                            predictor=None, random_state=None, ...))])

In [31]:
ensemble_predictions = ensemble.predict(x_test_n)
ensemble_accuracy = accuracy_score(y_test, ensemble_predictions)
cm=confusion_matrix(y_test,ensemble_predictions)
print(cm)
print(ensemble_accuracy)

[[39601  4798]
 [ 2376 41627]]
0.9188479898644827


In [32]:
from sklearn.ensemble import ExtraTreesClassifier


In [33]:
etc = ExtraTreesClassifier(n_estimators=200)

In [34]:
etc.fit(x_train_n, y_train)
y_pred=etc.predict(x_test_n)
accuracy_score(y_test,y_pred)

0.923700821248388